# This script is used to visualize the number of interface hydrogen bonds in final structures obtained from molecular dynamics simulations for Figure 1E, including three different temperatures: 280 K, 300 K, and 320 K.
# The final structures were generated by averaging the conformations from 45 ns to 50 ns of the MD simulations.

library(ggplot2)

# 1. Create data frame for the number of interface hydrogen bonds
# Data obtained from PyMOL analysis; PyMOL script is available in Figure1E_Interface_Hbonds_analysis.pml.
hb_data <- data.frame(
  temp = c("280K", "300K", "320K"),
  value = c(11, 11, 7)
)

# 2. Figure 1E: Interface Hydrogen Bonds at different temperatures
ggplot(hb_data, aes(x = temp, y = value, fill = temp)) +
  geom_col(width = 0.3, show.legend = FALSE) +
  geom_text(aes(label = value), vjust = -0.5, size = 4) +
  scale_fill_manual(values = c("280K"="#6090C1", "300K"="#fee395", "320K"="#f2724D")) +
  labs(x = "Temperature", y = "Number of Interface Hydrogen Bonds", title = "Interface Hydrogen Bonds") +
  scale_y_continuous(limits = c(0, 14), expand = c(0, 0)) +
  theme_bw() +
  theme(
    plot.title = element_text(face="bold", size=14, hjust=0.5),
    axis.title.x = element_text(size=12),
    axis.title.y = element_text(size=12),
    axis.text = element_text(size=11),
    legend.position = "none"
  )
