# This script is used to visualize the secondary structure composition of final structures obtained from molecular dynamics simulations for Figure 1F, including three different temperatures: 280 K, 300 K, and 320 K.
# The final structures were generated by averaging the conformations from 45 ns to 50 ns of the MD simulations.
# Secondary structure components include α-helix, β-sheet, and random coil.
# Data represent the percentage of each secondary structure type (total residues = 396).

library(ggplot2)
library(dplyr)
library(tidyr)

# 1. Create data frame for secondary structure composition
# Data were obtained from the final averaged structures, using DSSP at PDBsum website.
# Total residues: 396
ss_data <- data.frame(
  temp = c("280K", "300K", "320K"),        # Temperature conditions
  Helix = c(164, 151, 147),                # Number of α-helix residues
  Sheet = c(22, 22, 22),                   # Number of β-sheet residues
  Coil = c(210, 223, 227)                  # Number of random coil residues
)

# 2. Convert to long format and calculate percentage
ss_long <- ss_data %>%
  pivot_longer(cols = c(Helix, Sheet, Coil),
               names_to = "Structure",
               values_to = "Count") %>%
  group_by(temp) %>%
  mutate(Percent = Count / sum(Count) * 100) %>%  # Calculate percentage
  ungroup()

# 3. Set fixed order for secondary structure categories
ss_long$Structure <- factor(ss_long$Structure,
                            levels = c("Helix", "Sheet", "Coil"))

# 4. Figure 1F: Stacked bar plot with percentage labels
ggplot(ss_long, aes(x = temp, y = Count, fill = Structure)) +
  geom_col(position = "stack", width = 0.5) +
  
  # Show percentage inside each bar segment (1 decimal place)
  geom_text(aes(label = sprintf("%.1f%%", Percent)), 
            position = position_stack(vjust = 0.5), 
            size = 4, color = "black") +
  
  # Consistent color scheme
  scale_fill_manual(values = c("Helix"  = "#f2724D", 
                               "Sheet" = "#fee395", 
                               "Coil"  = "#6090C1")) +
  
  scale_y_continuous(limits = c(0, 400), expand = c(0, 0)) +
  
  # Labels
  labs(x = "Temperature",
       y = "Number of Residues",
       fill = "Secondary Structure",
       title = "Secondary Structure of MD Final Structures") +
  
  theme_bw() +
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text = element_text(size = 11),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9)
  )
